### ISSUE TITLE
where to download the data for Isotropic Reconstruction

### ISSUE THREAD

**Issue by raynehe** [Luchixiang/EMDiffuse#2]
Hi! Thanks for the wonderful work!

Sorry for the bother, I'm a little confused about the dataset for isotropic reconstruction. When I download the [MICrONS](https://www.microns-explorer.org/) and [Openorgnelle liver dataset](https://open.quiltdata.com/b/janelia-cosem-datasets/tree/jrc_mus-liver/jrc_mus-liver.n5/), neither of them appears in the required data structure format. 

Also, for [FANC dataset](https://bossdb.org/project/phelps_hildebrand_graham2021), am I suppose to download the dataset, or can I simply import the data using `channel = array("bossdb://phelps_hildebrand_graham2021/FANC/em")`?

I'm wondering if you could kindly provide a more detailed instruction about the downloading of these three datasets, such as the specific download webpage link.

Sorry again for the bother!

**Comment by Luchixiang** [comment]
It does need some pre-processing procedure to sort the vem data into the format EMDiffuse accepts. You can download the volume from the website such as ```em = array("bossdb://phelps_hildebrand_graham2021/FANC/em")``` and then crop the volume ``` em[z_start:z_start + train_z_patch_size , y_start:y_start + train_patch_size, x_start:x_start + train_patch_size]``` (for example train_patch_size=2048). Then split the volume into single 2D tif:        
``` 
for i in range(train_z_patch_size):
    img_slice = img_sample[i, :, :]
    imwrite(os.path.join(save_path, str(i) + '.tif'), img_slice)```

**Comment by raynehe** [comment]
Thanks for your timely help!

Sorry to interrupt again. I'm still a little confused about how to set the parameters. When I download the FANC dataset using:
```python
save_path='/home/rayne/datasets/EMDiffuse/isotropic_reconstruction/FANC'
os.makedirs(save_path, exist_ok=True)

em = array("bossdb://phelps_hildebrand_graham2021/FANC/em")

z_start=1000
y_start=1000
x_start=1000
train_z_patch_size=256
train_patch_size=2048
img_sample = em[z_start:z_start + train_z_patch_size , y_start:y_start + train_patch_size, x_start:x_start + train_patch_size]

# split
for i in range(train_z_patch_size):
    img_slice = img_sample[i, :, :]
    imwrite(os.path.join(save_path, str(i) + '.tif'), img_slice)
```

I got completely black images, I'm wondering whether I've set the parameters (`z_start` and so on) wrong. Could you give me a hint about it?

Or could you provide the download code for the MICrONS, Openorgnelle liver or FANC datasets? Thanks veeeeery much!

**Comment by Luchixiang** [comment]
Because the border region of the original dataset is completely black. You should set a larger x_start and y_start (e.g., 20000). Or you may select a region of interests you want to explore. You can get the preview of the dataset in neuronglance (https://neuroglancer.bossdb.io/#!%7B%22layers%22:%5B%7B%22source%22:%22boss://https://api.bossdb.io/phelps_hildebrand_graham2021/FANC/em%22%2C%22type%22:%22image%22%2C%22name%22:%22FANC%22%7D%5D%2C%22navigation%22:%7B%22pose%22:%7B%22position%22:%7B%22voxelSize%22:%5B4.300000190734863%2C4.300000190734863%2C45%5D%2C%22voxelCoordinates%22:%5B23697.609375%2C116496.1171875%2C1228%5D%7D%7D%2C%22zoomFactor%22:8.154868142736303%7D%2C%22showAxisLines%22:false%2C%22layout%22:%22xy%22%7D). The x y corrdinate is shown on the top left corner
